hw10/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

quotes/urls.py
from django.urls import path, include

from . import views

app_name = "quotes"
 
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:page>', views.index, name="root_paginate"),
    path('users/', include('users.urls')),
    path("add_quote/", views.add_quote, name="add_quote"),
]

users/urls.py
from django.urls import path, include

from . import views

app_name = "users"
 
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout')
]

quotes/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

users/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=15)

quotes/forms.py
from django import forms

from .models import Quote, Author


class QuoteForm(forms.ModelForm):
    author = forms.ModelChoiceField(queryset=Author.objects.all(), empty_label="Виберіть автора", required=True)

    class Meta:
        model = Quote
        fields = ['author', 'quote', 'tags']
        widgets = {
            'quote': forms.Textarea(attrs={'rows': 3, 'placeholder': 'Введіть текст цитати'}),
            'tags': forms.TextInput(attrs={'placeholder': 'Введіть теги через кому'}),
        }

users/forms.py
from django import forms
from .models import User

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['name', 'password']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError("Passwords do not match!")

quotes/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from pymongo import MongoClient

from .utils import get_mongodb
from .forms import QuoteForm

client = MongoClient("mongodb://localhost")
db = client.HW_10


def index(request, page=1):
    db = get_mongodb()
    quotes = db.quotes.find()
    per_page = 10
    paginator = Paginator(list(quotes), per_page=per_page)
    quotes_on_page = paginator.page(page)
    
    return render(request, 'quotes/index.html', context={'quotes' : quotes_on_page})


@login_required
def add_quote(request):
    if request.method == "POST":
        author_f = request.POST['author']
        quote = request.POST['quote']
        tags = request.POST['tags']

        if db.authors.find_one({'fullname' : author_f}):
            db.quotes.insert_one({
                'author' : author_f,
                'quote' : quote,
                'tags' : tags,
            })
            return redirect('quotes:index') 
        else:
            return
    else:
        form = QuoteForm()

    return render(request, "quotes/add_quote.html", {"form": form})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.http import HttpResponse
from pymongo import MongoClient

client = MongoClient("mongodb://localhost")
db = client.HW_10


def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)

            if not db.users.find_one({"username": username}):
                db.users.insert_one({
                    "username": username,
                    "password": password,
                    "is_authenticated": True
                })

            return redirect("quotes:index")
        else:
            return HttpResponse("Невірний логін чи пароль")
    return render(request, "users/login.html")


def logout_view(request):
    logout(request)
    return redirect("quotes:index")

quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}
<div class="container mt-5">
    <h2>Додати нову цитату</h2>
    <form method="post">
        {% csrf_token %}
        
        <div class="form-group">
            {{ form.author.label }} <!-- Відображаємо мітку для поля автор -->
            {{ form.author }}  <!-- Відображаємо поле для автора -->
        </div>

        <div class="form-group">
            {{ form.quote.label }} <!-- Відображаємо мітку для поля цитати -->
            {{ form.quote }} <!-- Відображаємо поле для цитати -->
        </div>
        
        <div class="form-group">
            {{ form.tags.label }} <!-- Відображаємо мітку для поля тегів -->
            {{ form.tags }} <!-- Відображаємо поле для тегів -->
        </div>

        <!-- Кнопка для відправлення форми -->
        <button type="submit" class="btn btn-success">Зберегти</button>
        
        <!-- Кнопка для скасування -->
        <a href="{% url 'quotes:index' %}" class="btn btn-secondary">Скасувати</a>
    </form>
</div>
{% endblock %}

quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>HomeWork10</title>
</head>
<body>
<div class="container">
    <div class="row header-box pt-3">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4">
            <p>
                {% if user.is_authenticated %}
                    <a href="/">{{user.username}}</a>
                    <a href="{% url 'users:logout' %}" class="btn btn-dark">Logout</a>
                {% else %}
                    <a href="{% url 'users:login' %}" class="btn btn-success">Login</a>
                {% endif %}
            </p>
        </div>
        <div class="container mt-3">
            {% if user.is_authenticated %}
                <a href="{% url 'quotes:add_quote' %}" class="btn btn-success">Add Quote</a>
            {% else %}
                <a href="{% url 'users:login' %}?next={% url 'quotes:add_quote' %}" class="btn btn-primary">Add Quote</a>
            {% endif %}
        </div>

    {% block content %} {% endblock %}

</div>
</body>
</html>

quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
            <a href="/author/{{quote.author}}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags%}
                <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <nav>
        <ul class="pager">
            
            <li class="previous">
            <a class='{% if not quotes.has_previous %} disabled {% endif %}' 
                href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous</a>
            </li>
            
            
            <li class="next">
                <a class='{% if not quotes.has_previous %} disabled {% endif %}' 
                href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">Next 
                    <span aria-hidden="true">→</span></a>
            </li>
            
        </ul>
        </nav>
    </div>
</div>

{% endblock %}

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Login</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <link rel="stylesheet" href="/static/main.css">
</head>

<body>
    <div class="container">
        <div class="row header-box">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                
                    <a href="{% url 'users:login' %}">Login</a>
                
                </p>
            </div>
        </div>
    

        <form action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>
            <button type="submit">Login</button>
        </form>


    </div>
</body></html>